[package]
name = "shar_search"
version = "0.1.0"
authors = ["Clement Tsang <cjhtsang@uwaterloo.ca>"]
license = "MIT"
edition = "2021"
readme = "README.md"

[dev-dependencies]
criterion = "=0.4.0"

[[bench]]
name = "std_compare"
harness = false
